CATEGORIZED_QUESTIONS = {
    "PYTHON": [
        {"text": "Which company developed the Python language?", "options": ["Google", "Microsoft", "Sun Microsystems", "Guido van Rossum"], "answer": "Guido van Rossum"},
        {"text": "Which keyword is used to define a function in Python?", "options": ["function", "func", "define", "def"], "answer": "def"},
        {"text": "Which operator is used for exponentiation in Python?", "options": ["^", "**", "//", "exp"], "answer": "**"},
        {"text": "In Python, which built-in function returns the length of a list?", "options": ["length()", "size()", "count()", "len()"], "answer": "len()"},
        {"text": "What is the correct way to create a list in Python?", "options": ["list = (1, 2, 3)", "list = [1, 2, 3]", "list = {1, 2, 3}", "list = <1, 2, 3>"], "answer": "list = [1, 2, 3]"},
        {"text": "How do you start a comment in Python?", "options": ["//", "/*", "#", "--"], "answer": "#"},
        {"text": "Which of these data types is immutable in Python?", "options": ["List", "Dictionary", "Set", "Tuple"], "answer": "Tuple"},
        {"text": "What is the output of bool([]) in Python?", "options": ["True", "False", "Error", "None"], "answer": "False"},
        {"text": "Which method is used to add an element to the end of a list in Python?", "options": ["add()", "push()", "append()", "insert()"], "answer": "append()"},
        {"text": "What does the 'self' keyword represent in a Python class?", "options": ["The class itself", "The parent class", "The instance of the class", "A global variable"], "answer": "The instance of the class"},
        {"text": "Which of these is used for list comprehension in Python?", "options": ["[x for x in list]", "{x for x in list}", "(x for x in list)", "None of these"], "answer": "[x for x in list]"},
        {"text": "What is the purpose of the '__init__' method in Python?", "options": ["To initialize a list", "To initialize a class instance", "To initialize a module", "To initialize a function"], "answer": "To initialize a class instance"},
        {"text": "In Python, how do you raise an exception?", "options": ["throw Exception", "raise Exception", "catch Exception", "try Exception"], "answer": "raise Exception"},
        {"text": "Which module in Python is used for regular expressions?", "options": ["regex", "re", "pyregex", "reg"], "answer": "re"},
        {"text": "What does the 'len()' function do in Python?", "options": ["Returns the size of memory", "Returns the number of items in an object", "Returns the length of a number", "Returns the sum of elements"], "answer": "Returns the number of items in an object"}
    ],
    "JAVA": [
        {"text": "Which of these is NOT a primitive data type in Java?", "options": ["int", "char", "String", "boolean"], "answer": "String"},
        {"text": "Which keyword is used to inherit a class in Java?", "options": ["extends", "implements", "inherits", "using"], "answer": "extends"},
        {"text": "What is the entry point of a Java application?", "options": ["main() method", "init() method", "start() method", "run() method"], "answer": "main() method"},
        {"text": "Which company originally developed Java?", "options": ["Microsoft", "Google", "Sun Microsystems", "Oracle"], "answer": "Sun Microsystems"},
        {"text": "In Java, what is the default value of a boolean variable?", "options": ["true", "false", "null", "undefined"], "answer": "false"},
        {"text": "Which collection in Java allows unique elements only?", "options": ["ArrayList", "LinkedList", "HashSet", "Vector"], "answer": "HashSet"},
        {"text": "What is the purpose of the 'final' keyword in Java?", "options": ["To end a loop", "To make a variable constant", "To end a program", "ToEnd a class"], "answer": "To make a variable constant"},
        {"text": "How do you handle exceptions in Java?", "options": ["try-catch block", "if-else block", "for-each block", "switch block"], "answer": "try-catch block"},
        {"text": "Which keyword is used to access the parent class in Java?", "options": ["this", "parent", "super", "base"], "answer": "super"},
        {"text": "In Java, what does JVM stand for?", "options": ["Java Variable Machine", "Java Virtual Machine", "Java Visual Monitor", "Java Verified Model"], "answer": "Java Virtual Machine"},
        {"text": "Which access modifier gives the widest visibility in Java?", "options": ["private", "protected", "public", "default"], "answer": "public"},
        {"text": "Which of these is used to compile Java code?", "options": ["java", "javac", "jvm", "javadoc"], "answer": "javac"},
        {"text": "What is an interface in Java?", "options": ["A type of class", "A blueprint for classes", "A variable", "A loop"], "answer": "A blueprint for classes"},
        {"text": "Which Java version introduced Lambda expressions?", "options": ["Java 6", "Java 7", "Java 8", "Java 9"], "answer": "Java 8"},
        {"text": "What is a 'null' in Java?", "options": ["A zero value", "An empty string", "A reference that points to nothing", "An error"], "answer": "A reference that points to nothing"}
    ],
    "JAVASCRIPT": [
        {"text": "In JavaScript, which function is used to print to the console?", "options": ["print()", "echo()", "console.log()", "system.out.println()"], "answer": "console.log()"},
        {"text": "Which keyword is used to declare a block-scoped variable in JavaScript?", "options": ["var", "let", "const", "Both let and const"], "answer": "Both let and const"},
        {"text": "What does the '===' operator do in JavaScript?", "options": ["Checks for value equality only", "Checks for value and type equality", "Assigns a value", "None of these"], "answer": "Checks for value and type equality"},
        {"text": "Which method is used to add an element to the end of an array in JavaScript?", "options": ["add()", "push()", "append()", "insert()"], "answer": "push()"},
        {"text": "How do you create a function in JavaScript?", "options": ["function myFunc()", "def myFunc()", "func myFunc()", "void myFunc()"], "answer": "function myFunc()"},
        {"text": "What is a 'Promise' in JavaScript?", "options": ["A commitment to finish code", "An object representing future completion of an async operation", "A type of loop", "A syntax error"], "answer": "An object representing future completion of an async operation"},
        {"text": "Which company developed JavaScript?", "options": ["Microsoft", "Netscape", "Google", "Mozilla"], "answer": "Netscape"},
        {"text": "What does DOM stand for?", "options": ["Document Object Model", "Dynamic Object Model", "Data Object Mode", "Document Oriented Model"], "answer": "Document Object Model"},
        {"text": "Which of these is NOT a JavaScript framework?", "options": ["React", "Angular", "Vue", "Django"], "answer": "Django"},
        {"text": "In JS, 'NaN' stands for?", "options": ["Not a Number", "New and Notary", "Native and New", "None and Null"], "answer": "Not a Number"},
        {"text": "How do you write an arrow function in JavaScript?", "options": ["() -> {}", "() => {}", "func => {}", "=> () {}"], "answer": "() => {}"},
        {"text": "Which event occurs when the user clicks on an HTML element?", "options": ["onclick", "onmouseclick", "onchange", "onmouseover"], "answer": "onclick"},
        {"text": "What is the purpose of 'use strict' in JavaScript?", "options": ["To use a strict compiler", "To enforce stricter parsing and error handling", "To make code run faster", "To enable new features"], "answer": "To enforce stricter parsing and error handling"},
        {"text": "How do you check the type of a variable in JS?", "options": ["getType()", "typeOf()", "typeof", "variable.type"], "answer": "typeof"}
    ],
    "SQL": [
        {"text": "What does SQL stand for?", "options": ["Simple Query Language", "Structured Query Language", "Socket Query Level", "Standard Quick Link"], "answer": "Structured Query Language"},
        {"text": "Which SQL statement is used to extract data from a database?", "options": ["SELECT", "EXTRACT", "GET", "OPEN"], "answer": "SELECT"},
        {"text": "Which SQL statement is used to update data in a database?", "options": ["UPDATE", "MODIFY", "SAVE", "CHANGE"], "answer": "UPDATE"},
        {"text": "Which SQL statement is used to delete data from a database?", "options": ["DELETE", "REMOVE", "DROP", "TRUNCATE"], "answer": "DELETE"},
        {"text": "What is the primary role of a 'Primary Key' in a database?", "options": ["Encrypt the data", "Uniquely identify a record", "Link to a foreign key", "Store large images"], "answer": "Uniquely identify a record"},
        {"text": "Which of the following is a NoSQL database?", "options": ["PostgreSQL", "MySQL", "MongoDB", "Oracle"], "answer": "MongoDB"},
        {"text": "In SQL, which clause is used to filter records?", "options": ["WHERE", "FILTER", "HAVING", "GROUP BY"], "answer": "WHERE"},
        {"text": "Which SQL command is used to remove a table and its data?", "options": ["DELETE", "REMOVE", "DROP", "TRUNCATE"], "answer": "DROP"},
        {"text": "What does the JOIN clause do in SQL?", "options": ["Removes duplicates", "Combines rows from two or more tables", "Sorts the data", "Filters the data"], "answer": "Combines rows from two or more tables"},
        {"text": "Which aggregate function returns the number of rows in SQL?", "options": ["SUM()", "TOTAL()", "COUNT()", "ROWS()"], "answer": "COUNT()"},
        {"text": "How do you sort the results of a SELECT statement?", "options": ["ORDER BY", "SORT BY", "GROUP BY", "ARRANGE BY"], "answer": "ORDER BY"},
        {"text": "Which SQL keyword is used to return only unique values?", "options": ["UNIQUE", "DISTINCT", "DIFFERENT", "SINGLE"], "answer": "DISTINCT"},
        {"text": "What is a Foreign Key?", "options": ["A key from another database", "A key used to link two tables", "An encrypted key", "A primary key in the same table"], "answer": "A key used to link two tables"}
    ],
    "DEV": [
        {"text": "What is the time complexity of searching in a Hash Map (average)?", "options": ["O(1)", "O(n)", "O(log n)", "O(n^2)"], "answer": "O(1)"},
        {"text": "What does HTTP stand for?", "options": ["HyperText Transfer Protocol", "High Tension Tech Protocol", "Hyper Transfer Text Page", "Hosted Text Typing Path"], "answer": "HyperText Transfer Protocol"},
        {"text": "What is the default port for a Flask application?", "options": ["80", "443", "5000", "8080"], "answer": "5000"},
        {"text": "In Docker, what is the name of the file used to define image steps?", "options": ["Containerfile", "ImageMaker", "Dockerfile", "BuildScript"], "answer": "Dockerfile"},
        {"text": "Which data structure follows LIFO (Last In First Out)?", "options": ["Queue", "Stack", "Linked List", "Binary Tree"], "answer": "Stack"},
        {"text": "What does JSON stand for?", "options": ["Java Standard Object Notation", "JavaScript Object Notation", "Jolly Software Object Network", "Just Simple Object Node"], "answer": "JavaScript Object Notation"},
        {"text": "Which Git command is used to record changes in the repository?", "options": ["git record", "git save", "git commit", "git log"], "answer": "git commit"},
        {"text": "What is the purpose of 'git push'?", "options": ["Upload local changes to remote", "Download remote changes", "Delete local branch", "Create a new repo"], "answer": "Upload local changes to remote"},
        {"text": "What does API stand for?", "options": ["Automatic Program Interface", "Application Programming Interface", "Advanced Plugin Integration", "App Protocol Information"], "answer": "Application Programming Interface"},
        {"text": "Which HTTP method is used to update an existing resource?", "options": ["GET", "POST", "PUT", "DELETE"], "answer": "PUT"},
        {"text": "What is the binary representation of decimal 5?", "options": ["100", "111", "101", "011"], "answer": "101"},
        {"text": "Which tag is used for the largest heading in HTML?", "options": ["<h6>", "<head>", "<h10>", "<h1>"], "answer": "<h1>"},
        {"text": "What is 'CI/CD' stand for?", "options": ["Continuous Integration/Continuous Deployment", "Code Inspection/Code Delivery", "Critical Integration/Critical Design", "None of these"], "answer": "Continuous Integration/Continuous Deployment"},
        {"text": "What is the purpose of a Load Balancer?", "options": ["To encrypt data", "To distribute network traffic across multiple servers", "To back up data", "To speed up code execution"], "answer": "To distribute network traffic across multiple servers"},
        {"text": "What is a 'Unit Test'?", "options": ["Testing the whole application", "Testing a single unit or component", "Testing the UI only", "Testing database performance"], "answer": "Testing a single unit or component"},
        {"text": "In CSS, what property is used to change font color?", "options": ["font-color", "color", "text-style", "background-color"], "answer": "color"},
        {"text": "Which of these is a version control system?", "options": ["Docker", "Kubernetes", "Git", "Jenkins"], "answer": "Git"},
        {"text": "What does CPU stand for?", "options": ["Central Processing Unit", "Computer Personal Unit", "Central Peripheral Utility", "Core Process Unit"], "answer": "Central Processing Unit"},
        {"text": "What is the purpose of the 'Head' tag in HTML?", "options": ["To define the main content", "To contain descriptive information about the document", "To create a header", "To make text bold"], "answer": "To contain descriptive information about the document"},
        {"text": "Which protocol is used for sending emails?", "options": ["HTTP", "FTP", "SMTP", "SSH"], "answer": "SMTP"}
    ]
}

